// 图文并茂的内容策略规划

interface VisualContentPlan {
  section: string
  textContent: number
  visualElements: VisualElement[]
  layout: string
  seoOptimization: string[]
}

interface VisualElement {
  type: "image" | "icon" | "illustration" | "screenshot" | "animation" | "chart"
  description: string
  altText: string
  purpose: string
}

const visualContentStrategy: VisualContentPlan[] = [
  {
    section: "Hero Section",
    textContent: 120,
    layout: "split-hero-with-visual",
    visualElements: [
      {
        type: "illustration",
        description: "AI机器人创建PPT的动态插图",
        altText: "AI PPT Maker powered presentation generator creating professional slides",
        purpose: "视觉化展示AI创建演示文稿的过程",
      },
      {
        type: "screenshot",
        description: "实际生成的精美PPT截图",
        altText: "Professional PowerPoint slides created by AI presentation maker",
        purpose: "展示最终产品质量",
      },
    ],
    seoOptimization: ["图片alt标签包含主关键词", "文件名优化", "图片压缩优化加载速度"],
  },

  {
    section: "Trust Indicators",
    textContent: 80,
    layout: "stats-with-icons",
    visualElements: [
      {
        type: "icon",
        description: "用户图标配合数字统计",
        altText: "10M+ users trust our AI PPT Maker",
        purpose: "视觉化用户数量",
      },
      {
        type: "chart",
        description: "幻灯片生成量增长图表",
        altText: "120M+ slides generated by AI presentation maker",
        purpose: "展示平台活跃度",
      },
      {
        type: "image",
        description: "知名企业Logo墙",
        altText: "Companies using AI powerpoint generator",
        purpose: "建立权威性和信任度",
      },
    ],
    seoOptimization: ["Logo图片包含公司名称alt标签", "统计图表数据结构化标记"],
  },

  {
    section: "Templates Showcase",
    textContent: 150,
    layout: "interactive-gallery",
    visualElements: [
      {
        type: "screenshot",
        description: "商务模板预览图集",
        altText: "Business AI PPT Maker templates for professional presentations",
        purpose: "展示模板多样性",
      },
      {
        type: "screenshot",
        description: "教育类模板展示",
        altText: "Educational presentation templates from AI presentation maker",
        purpose: "覆盖教育用户群体",
      },
      {
        type: "animation",
        description: "模板切换动画效果",
        altText: "Interactive template preview in AI powerpoint generator",
        purpose: "提升用户体验",
      },
    ],
    seoOptimization: ["模板分类页面内链", "模板名称包含关键词", "懒加载优化"],
  },

  {
    section: "Features & Benefits",
    textContent: 200,
    layout: "feature-grid-with-visuals",
    visualElements: [
      {
        type: "icon",
        description: "AI大脑图标",
        altText: "AI-powered presentation maker intelligence",
        purpose: "突出AI技术特色",
      },
      {
        type: "illustration",
        description: "文件转换流程图",
        altText: "PDF to PPT conversion with AI PPT Maker",
        purpose: "展示转换功能",
      },
      {
        type: "screenshot",
        description: "编辑界面截图",
        altText: "User-friendly AI presentation maker interface",
        purpose: "展示易用性",
      },
    ],
    seoOptimization: ["功能图标SVG格式优化", "界面截图包含产品名称"],
  },

  {
    section: "Use Cases & Industries",
    textContent: 180,
    layout: "tabbed-visual-content",
    visualElements: [
      {
        type: "illustration",
        description: "不同行业应用场景插图",
        altText: "AI PPT Maker use cases for business education marketing",
        purpose: "可视化应用场景",
      },
      {
        type: "screenshot",
        description: "行业特定PPT示例",
        altText: "Industry-specific presentations made with AI powerpoint generator",
        purpose: "展示行业适用性",
      },
    ],
    seoOptimization: ["行业关键词融入alt标签", "场景图片本地化存储"],
  },

  {
    section: "How It Works",
    textContent: 160,
    layout: "step-by-step-visual",
    visualElements: [
      {
        type: "illustration",
        description: "4步骤流程图解",
        altText: "How AI PPT Maker works: 4 simple steps to create presentations",
        purpose: "简化理解过程",
      },
      {
        type: "animation",
        description: "上传到生成的动画演示",
        altText: "AI presentation maker workflow animation",
        purpose: "动态展示操作流程",
      },
      {
        type: "screenshot",
        description: "每个步骤的界面截图",
        altText: "AI PPT Maker interface screenshots showing creation process",
        purpose: "真实操作预览",
      },
    ],
    seoOptimization: ["流程图包含步骤关键词", "动画优化加载性能"],
  },
]

export { visualContentStrategy }
